version: '3.8' 
services: 
  db: 
    image: postgres:17 
    restart: always 
    environment: 
      - POSTGRES_DB=db 
      - POSTGRES_USER=user 
      - POSTGRES_PASSWORD=password 
    ports: 
      - "5500:5432" 
    volumes: 
      - db_volume:/var/lib/postgresql/data 
volumes: 
  db_volume: 
    name: "postgres_volume"